// FRIEND ACTIONS
export const SELECT_FRIEND = 'SELECT_FRIEND';
export const ADD_FRIEND = 'ADD_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const SET_FRIENDS = 'SET_FRIENDS';
export const MARK_ONLINE_FRIEND = 'MARK_ONLINE_FRIEND';

// MESSAGE ACTIONS
export const SEND_MESSAGE = 'SEND_MESSAGE';

// LOCATION ACTIONS
export const LOCATE_MAIN_SCREEN = 'LOCATE_MAIN_SCREEN';

// ME ACTIONS
export const SET_NICKNAME = 'SET_NICKNAME';
